arch:
- aarch64
- amd64
description: A deluxe latency measurement tool
image: linuxserver/smokeping
init: false
map:
- path: /config
  read_only: false
  type: addon_config
- path: /data
  read_only: false
  type: data
name: SmokePing
ports:
  80/tcp: 7464
ports_description:
  80/tcp: HTTP
slug: smokeping
url: https://www.smokeping.org/
version: 2.9.0
webui: http://[HOST]:[PORT:80]/
